### ISSUE TITLE
Mongodb c# driver 1.9.2 GeoJsonPoint on updation error 16754

### ISSUE THREAD

**Issue by mycarevault** [rstam/SampleMongoDBApplication#1]
I tried updating GeoJsonPoint in mongodb document with c# driver 1.9.2. I can save and do query on it, but when i try updating the record i get the below error.

(Response was { "ok" : 1, "code" : 16754, "err" : "Can't parse geometry from element: ). I am not sure what iam doing wrong, requesting to illuminate me with your solution.

The below is the Model class
public class BooksLocation : IMongoEntity
{
    public ObjectId _id { get; set; }
    public string _accessId { get; set; }
    public string placename { get; set; }
    public GeoJsonPoint<GeoJson2DGeographicCoordinates> Location { get; set; }
} 
This is the method i am using to update info
public void UpdateBookLocation(string recordid, string lat, string Lang)
    {
        try
        {
            var _location = new GeoJsonPoint<GeoJson2DGeographicCoordinates>(new GeoJson2DGeographicCoordinates(double.Parse(Lang), double.Parse(lat)));
            var query = Query.EQ("_id", ObjectId.Parse(recordid));
            var updateValues = new List<UpdateBuilder>();
            updateValues.Add(Update.Set("Location", _location.ToBson()));
            IMongoUpdate update = Update.Combine(updateValues);
            uctx.BooksLocationCollection.Update(query, update);
        }
        catch (Exception ex)
        {
            throw (ex);
        }
    }

**Comment by rstam** [comment]
There's probably something wrong with the types which isn't being caught at compile time since you are using the untyped (non-generic) version of the builders.

It's usually easier and more reliable to use the typed API. Something like:

```
var query = Query<BooksLocation>.EQ(x => x._id, ObjectId.Parse(recordid);
var update = Update<BooksLocation>.Set(x => x.Location, _location);
uctx.BooksLocationCollection.Update(query, update);
```

**Comment by mycarevault** [comment]
rstam, Thanks your comments. I figured, that error was a TypeOf mismatch. I solved just giving the entire namespace "Location.coordinates.0". and your version seems pretty straight and clean.
Thanks again.
